### PR TITLE
Fix for MacOS where absolute path messes up because of filename conventions

### PR DESCRIPTION
**Pull request by ehildenb**
@mrchico this should address #21

### CODE REVIEW

**Comment by MrChico** [comment]
Hmmm, the problem persists when I try this branch

**Comment by MrChico** [comment]
Builds, but does not run. Am I missing some ocaml deps?
```
make test
./kwasm test tests/simple/arithmetic.wast
error loading shared library: dlopen(~/wasm-semantics/.build/defn/test/test-kompiled/realdef.cmxs, 10): Symbol not found: _caml_curry10
  Referenced from: ~/wasm-semantics/.build/defn/test/test-kompiled/realdef.cmxs
  Expected in: flat namespace
 in ~/wasm-semantics/.build/defn/test/test-kompiled/realdef.cmxsFatal error: exception Failure("could not load semantics")
[Error] Critical: Failed to execute program in ocaml. See output for error
information.
make: *** [tests/simple/arithmetic.wast.test] Error 113
```

**Comment by ehildenb** [comment]
It's going to be hard for me to figure this out without access to your system. Can you look at target `ocaml-deps` in the `Makefile` of `evm-semantics` and start to pull over packages installed on the last line into this `Makefile` one at a time to the `wasm-semantics` makefile in target `ocaml-deps`? Then run `make ocaml-deps ; make build ; make test`, and if it succeeds with some of those packages added then we can add it to the makefile for wasm.

**Comment by ehildenb** [comment]
This is fully subsumed by #38

**Pull request closed without merging**
